### ISSUE TITLE
Specify Content-Type for "content" property value

### ISSUE THREAD

**Issue by edwardanderson** [linked-art/linked.art#388] opened 2021-01-13 14:18 UTC
Do we have a way of providing the `Content-Type` of textual data carried in the `content` property? If text is, for example HTML or Markdown, can this type be specified?

```json
{
  "type": "LinguisticObject",
  "content": "<p>This text is <strong>significant</strong></p>"
}
```

**Comment by azaroth42** [comment] 2021-01-13 14:28
Assuming that the desired construction would be something like:

```
{
  "type": "LinguisticObject",
  "content": "<p>...</p>",
  "format": "text/html"
}
```

I think that we could use `dc:format` for the `format` property, as per its use for `DigitalObject` [here](https://linked.art/model/digital/).

**Comment by azaroth42** [comment] 2024-04-05 20:36
#565 is dupe of this

**Closed** 2024-04-05 21:07 UTC
Labels: enhancement, model, docs-needed
