### ISSUE TITLE
Make headers be anchor links to themselves

### ISSUE THREAD

**Issue by mdlincoln** [linked-art/linked.art#77] opened 2017-07-25 00:22 UTC
Right now I can copy the anchor link to a heading (e.g. <http://linked.art/model/object/identity/#titles>) from the ToC at the top of each page. It would be very useful to be able to copy the link while I'm actually looking at a header in place.

**Comment by azaroth42** [comment] 2017-08-25 21:03
Yep +1. Duplicate of #21. It comes from python's markdown processor deprecating the previous table of contents generator :(

**Closed by azaroth42** 2017-08-25 21:03 UTC
