### ISSUE TITLE
add rdfpuml images

### ISSUE THREAD

**Issue by VladimirAlexiev** [linked-art/linked.art#94] opened 2017-08-28 17:30 UTC
Got https://linked.art/example/object/16.ttl.
Added a global file prefixes.ttl with some aux prefixes (eg puml).
Added a few control statements like this.
```ttl
<http://vocab.getty.edu/aat/300014078> a puml:Inline.
<http://vocab.getty.edu/aat/300015045> a puml:Inline.
<http://vocab.getty.edu/aat/300033618> a puml:Inline.
<http://vocab.getty.edu/aat/300133025> a puml:Inline.
<http://vocab.getty.edu/aat/300014844> a puml:Inline.
```
Made it to an image with rdfpuml:
![16](https://user-images.githubusercontent.com/536250/29785325-d3666368-8c2f-11e7-8323-6014c1c81705.png)

@azaroth42 
- Do you find the images useful?
- Do you like the AAT concepts inlined, or as separate nodes?
- Noticed that 3 labels are missing, see https://github.com/linked-art/linked.art/issues/93.
- Where to put the control statements? We could put global AAT inlining in a global file, and if we need per-file tweaking (eg arrow directions), eg in 16.puml.ttl
- Guess we want another version displaying JSONLD prop & class names? It's a bigger question since rdfpuml can't do that (yet)

Someone asked for rdfpuml opensource (@workergnome has an old version), I'll post it when I find the time.

**Comment by azaroth42** [comment] 2017-08-28 17:32
Duplicate of #90.

**Closed by azaroth42** 2017-08-28 17:32 UTC

**Comment by VladimirAlexiev** [comment] 2017-08-29 07:48
@azaroth42 @workergnome Please answer the bullets above, esp about the style of rendering.

**Comment by workergnome** [comment] 2017-08-29 15:57
I think that RDFPUML is a useful tool, but I think it's probably more appropriate to work through these issues on a rdfpuml repository, not on this one.

**Comment by azaroth42** [comment] 2017-08-29 16:01
Do __I__ find them useful compared to nothing, yes. Do I think they're useful for the site, no, as per the top issue description in #90. 

In particular, the site is intended specifically to make it easy to implement __without__ understanding RDF at all. So the diagrams should follow the JSON, with hovers for the RDF predicates.

**Comment by VladimirAlexiev** [comment] 2017-08-30 12:53
These are questions about linked.art's use of rdfpuml, not rdfpuml itself:
- Do you like the AAT concepts inlined, or as separate nodes?
- Where to put the control statements? We could put global AAT inlining in a global file, and if we need per-file tweaking (eg arrow directions), eg in 16.puml.ttl

@azaroth42 Agree that to illustrate the JSONLD code, "JSONLD prop & class names" are required.
But I think that RDF images are also useful. So I think we should have both links: ... JSONLD Diagram ... Turtle Diagram.

puml has tooltips (hovers) over node, field, and edge: [see example](http://www.plantuml.com/plantuml/uml/RP0n3eCm34NtdC8Nw4373XLIbnwWdH13I4mRuSIH4mQ4k7i3T61W-_h_-GskKzQIHq_gwom2-fWdyEWxbBHNneaXJ2eDBaGjsiDpYYZaml1WOe6Ej1dEvdUmMq3eDILKof1E2G9Rl4BJp2zcoYu2ztktj2seDLLmkV-nMm6ZS37cwNY0zeE5Fpgh4sUrEc5MKBRU8TaZi1MhP54r1bkUy0C0)
Graphviz also: http://www.graphviz.org/doc/info/attrs.html#d:tooltip.
